# Generated by Django 2.1.4 on 2019-05-19 14:57

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('index', models.IntegerField(verbose_name='index')),
                ('document_id', models.CharField(max_length=25, verbose_name='document_id')),
                ('tei', models.TextField(verbose_name='tei')),
                ('context', models.TextField(verbose_name='context')),
                ('reference', models.TextField(verbose_name='reference')),
                ('chapter_number', models.IntegerField(null=True, verbose_name='chapter_number')),
                ('verse_number', models.IntegerField(null=True, verbose_name='verse_or_stanza_number')),
                ('line_number', models.IntegerField(verbose_name='line_or_verseline_number')),
                ('siglum', models.CharField(max_length=25, verbose_name='siglum')),
                ('document_type', models.TextField(verbose_name='document_type')),
                ('language', models.CharField(max_length=5, verbose_name='language')),
                ('duplicate_position', models.IntegerField(null=True, verbose_name='duplicate_position')),
                ('transcription_siglum', models.TextField(verbose_name='transcription_siglum')),
                ('transcription_identifier', models.TextField(verbose_name='transcription_identifier')),
                ('inscriptio', models.NullBooleanField(verbose_name='inscriptio')),
                ('subscriptio', models.NullBooleanField(verbose_name='subscriptio')),
                ('witnesses', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('public', models.BooleanField(verbose_name='public')),
            ],
            options={
                'ordering': ['chapter_number', 'verse_number', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('name', models.TextField(verbose_name='name')),
                ('abbreviation', models.TextField(verbose_name='abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(unique=True, verbose_name='identifier')),
                ('document_id', models.CharField(max_length=25, verbose_name='document_id')),
                ('tei', models.TextField(verbose_name='tei')),
                ('source', models.TextField(verbose_name='source')),
                ('siglum', models.CharField(max_length=25, verbose_name='siglum')),
                ('document_type', models.TextField(verbose_name='document_type')),
                ('corrector_order', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('total_collation_units', models.IntegerField(verbose_name='total_verses')),
                ('total_unique_collation_units', models.IntegerField(verbose_name='total_verses')),
                ('loading_complete', models.NullBooleanField(verbose_name='loading_complete')),
                ('public', models.BooleanField(verbose_name='public')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Collection')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('name', models.TextField(verbose_name='name')),
                ('abbreviation', models.TextField(verbose_name='abbreviation')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Collection')),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
        migrations.AddField(
            model_name='transcription',
            name='works',
            field=models.ManyToManyField(related_name='transcriptions', to='transcriptions.Work'),
        ),
        migrations.AddField(
            model_name='collationunit',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='transcriptions.Transcription'),
        ),
        migrations.AddField(
            model_name='collationunit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collationunit',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verse_details', to='transcriptions.Work'),
        ),
    ]
