# Generated by Django 2.1.4 on 2019-05-19 20:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='chapters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collationunit',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='transcriptions.Transcription'),
        ),
        migrations.AlterField(
            model_name='collationunit',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_units', to='transcriptions.Work'),
        ),
    ]
