# Generated by Django 2.1.4 on 2019-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_auto_20190519_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='main_language',
            field=models.TextField(default='ae', verbose_name='main_language'),
            preserve_default=False,
        ),
    ]
