# Generated by Django 2.1.4 on 2019-05-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_transcription_main_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='chapters',
        ),
    ]
