# Generated by Django 2.1.4 on 2019-05-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0004_remove_transcription_chapters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collationunit',
            options={'ordering': ['chapter_number', 'stanza_number', 'line_number']},
        ),
        migrations.RenameField(
            model_name='collationunit',
            old_name='verse_number',
            new_name='stanza_number',
        ),
    ]
