# Generated by Django 2.1.4 on 2019-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0005_auto_20190521_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collationunit',
            name='inscriptio',
        ),
        migrations.RemoveField(
            model_name='collationunit',
            name='subscriptio',
        ),
        migrations.AlterField(
            model_name='collationunit',
            name='document_id',
            field=models.TextField(verbose_name='document_id'),
        ),
        migrations.AlterField(
            model_name='collationunit',
            name='siglum',
            field=models.TextField(verbose_name='siglum'),
        ),
    ]
