# Generated by Django 2.1.4 on 2019-05-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0008_collationunit_equivalent_contexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collationunit',
            name='equivalent_contexts',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='works',
        ),
    ]
