# Generated by Django 2.1.4 on 2019-05-31 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0009_auto_20190531_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transcriptions', to='transcriptions.Work'),
            preserve_default=False,
        ),
    ]
