# Generated by Django 2.1.4 on 2019-05-31 13:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0010_transcription_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeremonyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yasna', models.TextField(verbose_name='context')),
                ('mappings', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
