# Generated by Django 2.1.4 on 2019-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0011_ceremonymapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceremonymapping',
            options={'ordering': ['chapter_number', 'stanza_number', 'line_number']},
        ),
        migrations.RenameField(
            model_name='ceremonymapping',
            old_name='yasna',
            new_name='context',
        ),
        migrations.AddField(
            model_name='ceremonymapping',
            name='chapter_number',
            field=models.IntegerField(default=0, verbose_name='chapter_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ceremonymapping',
            name='line_number',
            field=models.IntegerField(default=0, verbose_name='line_or_verseline_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ceremonymapping',
            name='stanza_number',
            field=models.IntegerField(default=0, verbose_name='verse_or_stanza_number'),
            preserve_default=False,
        ),
    ]
