# Generated by Django 2.1.4 on 2019-08-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0012_auto_20190605_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collationunit',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='document_type',
        ),
    ]
