# Generated by Django 2.1.4 on 2019-08-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0013_auto_20190822_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonymapping',
            name='context',
            field=models.TextField(unique=True, verbose_name='context'),
        ),
    ]
