# Generated by Django 2.1.4 on 2019-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0014_auto_20190824_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonymapping',
            name='context',
            field=models.TextField(verbose_name='context'),
        ),
    ]
