# Generated by Django 2.1.4 on 2019-09-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0016_auto_20190825_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['siglum']},
        ),
    ]
