# Generated by Django 2.1.4 on 2019-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0018_auto_20191107_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='collationunit',
            name='lacom_reason',
            field=models.TextField(default='', verbose_name='lacom_reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collationunit',
            name='language',
            field=models.TextField(verbose_name='language'),
        ),
    ]
