# Generated by Django 2.1.4 on 2019-11-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0019_auto_20191112_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collationunit',
            name='lacom_reason',
        ),
    ]
