# Generated by Django 2.2 on 2020-07-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0020_remove_collationunit_lacom_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='total_collation_units',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='total_unique_collation_units',
        ),
    ]
