# Generated by Django 3.2 on 2021-11-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0024_auto_20211022_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeremonyMapping',
        ),
    ]
